### ISSUE TITLE
Virus Detection in windows exe release

### ISSUE THREAD

**Issue by jonathanR79** [Dynatrace/dynatrace-configuration-as-code#374]
**Describe the bug**
Windows exe release files are detected as virus by Symantec Endpoint protection tool (Heur.AdvML.B).

I've submitted the file to Symantec for false positive review but it's not the only AV to detect it.

**How to reproduce**
The file can be submited to https://www.virustotal.com/ which also detect some issue.

![image](https://user-images.githubusercontent.com/23026548/124636159-84364600-de88-11eb-8861-58fdd2e00aef.png)

**Expected behavior**
No Virus detection.

**Environment (please complete the following information):**
 - OS: Windows
 - Tool version >1.5.2

**Comment by UnseenWizzard** [comment]
Hi @jonathanR79 - sorry this has taken a while since your report. 

As of the [latest 2.0.0 pre-release](https://github.com/Dynatrace/dynatrace-configuration-as-code/releases/tag/v2.0.0-rc.6) Windows binaries are signed by Dynatrace.

A run of virustotal for the amd64 executable still flags one scanner believing it is malicious: 
Trapmine - and AI-based detection tool - there is no information on how or even what that tool thinks is malicious about the executable, resulting in this false-positive. 
https://www.virustotal.com/gui/file/c2c366c9a8838067ca8e40ee4387b4cb6fdc5d67f0e6625657c1c706a51f7a13/detection

I'll be closing this report, as this is as good as we can get for flagging by virus scanners. 

Please be assured we take security seriously, applying scans to both our own code and dependencies and utilizing dependabot for automated updates of dependencies. 

For upcoming releases, you'll also always find a "dependencies-and-licenses.txt" SBOM listing all dependencies if you wish to verify the status of advisories for these yourself. 

Any security advisories for Monaco itself you'll find at: https://github.com/Dynatrace/dynatrace-configuration-as-code/security/advisories
