### ISSUE TITLE
Allow default values for json template variable

### ISSUE THREAD

**Issue by heydenb** [Dynatrace/dynatrace-configuration-as-code#436]
Yaml config
...
ACertainConfig:
- name: SomeName
- paramA: Some value

Json:
...
"url": "{{.paramA}}",
"method":{{.paramB:POST}}  //if no paramB defined use POST as default

Alternative:
In Yaml config foresee a defaults section/
....
defaults:
paramB:POST

ACertainConfig:
- name: SomeName
- paramA: Some value
- paramB: GET // overwrites the default

**Comment by UnseenWizzard** [comment]
Adding this feature is sadly deemed too much effort for the benefit it provides. 

Currently, monaco relies on default Go templating functionality, while this would mean extending templating beyond this. 

Additionally, using Go templating it is possible to achieve this already - albeit a bit less convenient.
As conditionals are possible in templating, it is possible to set `"method": "POST"` if the `paramB` property is not found, and otherwise set `"method": "{{ .paramB }}"`.

For more details on advanced templating see this guide: https://www.dynatrace.com/support/help/shortlink/configuration-as-code-advanced-use-case
