### ISSUE TITLE
Error deploying templates with monaco in processgroup-naming

### ISSUE THREAD

**Issue by pacoporro** [Dynatrace/dynatrace-configuration-as-code#909]
wrongly created

**Comment by pacoporro** [comment]
wrongly created

**Comment by UnseenWizzard** [comment]
Hi @pacoporro , I'll still reply because I already started typing and it might be helpful to others:

This is an Error returned by the Dynatrace API, not one of monaco. 
In general if you see a HTTP status code, especially a 400 Bad Request, there is likely something wrong in the JSON template. The response should generally point you to what does not match. 
For details on the payloads of the Dynatrace API see https://www.dynatrace.com/support/help/dynatrace-api
