### ISSUE TITLE
Value of key 'manifestVersion' has unexpected type

### ISSUE THREAD

**Issue by GarrettHaines** [Dynatrace/dynatrace-configuration-as-code#932]
When I try to use "monaco convert ...", I get the following error thrown:
`FATAL YAML file could not be parsed: cannot convert YAML on level 1: value of key 'manifestVersion' has unexpected type.`

The first line of my config YAML looks like this:
`manifestVersion: "1.0"`

I have also tried replacing it with:
`manifestVersion: 1.0`
and still get the same error.

Why is this happening?

**Comment by UnseenWizzard** [comment]
The error message could be clearer, but the issue is that you're trying to convert a v2 manifest file.
The convert command exists to convert v1 configurations to v2.

v1 configuration always contain a top-level list defining all configs, I assume that causes this parsing error - it expects a v1 config containing a list. The v2 manifest ist just a random file to the v1 converter.

What made you try and convert a v2 project to v2?
