### ISSUE TITLE
Question - How do you pass in the url value from an environment variable to the manifest.yaml

### ISSUE THREAD

**Issue by kbocock-krg** [Dynatrace/dynatrace-configuration-as-code#969]
**Before you proceed**
We are happy about your enhancement proposal, but we would like to discuss this with you. Please make sure you've opened a [discussion](https://github.com/dynatrace/dynatrace-configuration-as-code/discussions) and are creating this feature/improvement request as a result of it. Make sure to link discussion here. 

**Is your feature request related to a problem? Please describe.**
Using Monaco 2.0.0, and we are able to have the token be picked up from an env. The url value does not work at all. Please advise how we should manage multiple dynatrace environments with monaco? Ex. (NP and PROD)

**Describe the solution you'd like**
a Clear example of how to resolve this. 

**Describe alternatives you've considered**
Jinja2 templating the manifest file. Works but not great.

**Comment by UnseenWizzard** [comment]
Hi @kbocock-krg, it is already possible to define an environment URL via environment variables. 

See the documentation: 
https://www.dynatrace.com/support/help/shortlink/configuration-as-code-configuration#environment-definition

And here's a sample manifest defining several environments (and env groups) that uses env vars for all URLs and Tokens/Secrets: 
https://github.com/Dynatrace/dynatrace-configuration-as-code/blob/main/cmd/monaco/integrationtest/v2/test-resources/integration-multi-project/manifest.yaml

I hope that helps! 

If I misunderstood your issue, please let me know and attach a sample of your failing configuration and logs.

**Comment by UnseenWizzard** [comment]
Are you still facing issues with this @kbocock-krg ?

**Comment by kbocock-krg** [comment]
We leveraged Jinja2 to overcome this issue and control the environment name by our workflow. We now have 1 file with a single clean responsibility and interface. Thank you for responding so quickly. I do hope to see the v1 environment globals come back. Right now the parameters in the corresponding id block of the configuration is a DRY violation. We need to create several hundred resources from code so our concern here is maintenance. Have you considered creating an ansible module which could also help with cleanup etc?

**Comment by UnseenWizzard** [comment]
Ah, now I see what you wanted to template in the manifest. 

In general, the way you use monaco - define things once, then template to create different configs at run time - is different from the core use-case we see for it. 
We aim for a main use-case of configuration as code as a gitops "source of truth," - so there are several decisions in v2 that make things more explicit and easier to reason about and review by just looking at config files (rather than how the CLI is called). 
These decisions make things more verbose - and thus go against your desire to keep configs for your use-case DRY.

---

We are looking into better covering such 'templating at scale' use-cases like yours in a way that keeps the core of monaco configuration explicit (and verbose) but still makes handling large amounts of similar configurations like you do as simple as possible.
